version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=/data/recipes.db
